### ISSUE TITLE
[not an issue] Snapcast dev branch is using your UI

### ISSUE THREAD

**Issue by badaix** [derglaus/snapcast-websockets-ui#3]
Hi glaus, 
I'm currently implementing native websocket support in Snapcast and found your UI as good and working test case (I had to change the socket from binary to text mode).
I've just commited a first draft, where your UI is dropped in: fa508eafba9a8b3efeb6a9b7d5d71aab5c984c30
Just to let you know :wink: 
Thanks for this nice UI :+1: 

To actually report an issue: it seems that the UI cannot handle [json rpc batch requests](https://www.jsonrpc.org/specification#batch) as sent by Snapcast when multiple client volume settings are changed

**Comment by derglaus** [comment]
Hi badaix,

I'm happy that you like the interface :)
If you want you can include it not only for testing purpose. I then suggest the interface to be maintained within the snapcast project.
If I find the time I will set up a dev-snapcast, reproduce the batch-json and implement a solution. Or anyone else who is faster than me, since I am currently quite busy. Thats why maintaining the interface as part of Snapcast may be the better solution...

**Comment by Error-101** [comment]
Hi @badaix and @derglaus. 

I have a fix for the batch jsonrcp requests. Look at the above pull request.

Apologies for the spelling in the commit.

**Comment by derglaus** [comment]
Hi Error-101,
Thank you very much for the fix :)
I'm currently on holiday,  so I can't check it, but it looks good :)

**Comment by badaix** [comment]
thanks @derglaus, for the moment I would like to stick to the current approach, to have a simple (don't take this offending, it's a big advantage) single file example for a websocket client, that I can use for testing and maybe others can use it as a template to develop their own UI.
